[package]
name = "zorilla-cli"
version = "0.1.3"
description = "CLI for zorilla — pytest test-smell linter"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "zorilla"
path = "src/main.rs"

[dependencies]
zorilla-core = { path = "../zorilla-core" }
clap = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
assert_cmd = { workspace = true }
predicates = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
